"""Trend engine — turns the accumulated deal log into board-grade statistics.

This is the part of the brief a competitor cannot replicate by subscribing to
the same newsletters. Every edition writes structured transaction records to
data/memory.json; over months that becomes a proprietary comparables database.
This module reads it and computes movement — median yields by sector and state,
direction against the prior cohort, deal counts, price ranges.

Everything here is computed in plain Python, never generated by a model. That
is deliberate: these are the numbers a CEO may repeat in a board meeting, so
they must be arithmetic on recorded data, not a language model's recollection
of it. The editor is given the finished figures and told not to recompute them.

Output is a small dict the editor renders, plus a deterministic HTML block.
"""

import statistics
from collections import defaultdict
from datetime import datetime, timedelta

# Don't publish a "median" off one or two data points — it reads as authority
# the sample doesn't support.
MIN_SAMPLE = 3
# Current cohort vs the preceding one, for direction.
RECENT_DAYS = 90
PRIOR_DAYS = 180

SECTOR_LABEL = {
    "retail": "Retail", "office": "Office", "industrial": "Industrial",
    "childcare": "Childcare", "aged_care": "Aged care", "other": "Other",
}


def _num(v):
    try:
        f = float(v)
        return f if f > 0 else None
    except (TypeError, ValueError):
        return None


def _cohort(items, start_days, end_days, today):
    lo = (today - timedelta(days=start_days)).strftime("%Y-%m-%d")
    hi = (today - timedelta(days=end_days)).strftime("%Y-%m-%d")
    return [i for i in items if hi > i.get("date", "") >= lo] if end_days else \
           [i for i in items if i.get("date", "") >= lo]


def compute(mem: dict, today: datetime | None = None) -> dict:
    """Return trend statistics, or an empty dict while the database is thin."""
    today = (today or datetime.now()).date()
    items = [i for i in mem.get("items", [])
             if isinstance(i, dict) and i.get("status") == "sold"]

    recent = _cohort(items, RECENT_DAYS, 0, today)
    prior = _cohort(items, PRIOR_DAYS, RECENT_DAYS, today)

    out = {
        "total_tracked": len(items),
        "recent_count": len(recent),
        "window_days": RECENT_DAYS,
        "sectors": [],
        "states": [],
        "largest": None,
    }
    if not recent:
        return out

    def yields_for(rows, key, val):
        return [y for r in rows if r.get(key) == val
                and (y := _num(r.get("yield_pct"))) is not None]

    for sector in sorted({r.get("sector") for r in recent if r.get("sector")}):
        cur = yields_for(recent, "sector", sector)
        if len(cur) < MIN_SAMPLE:
            continue
        entry = {
            "sector": SECTOR_LABEL.get(sector, str(sector).title()),
            "n": len(cur),
            "median_yield": round(statistics.median(cur), 2),
            "range": (round(min(cur), 2), round(max(cur), 2)),
            "shift_bps": None,
        }
        was = yields_for(prior, "sector", sector)
        if len(was) >= MIN_SAMPLE:
            entry["shift_bps"] = round(
                (statistics.median(cur) - statistics.median(was)) * 100)
        out["sectors"].append(entry)

    for state in sorted({r.get("state") for r in recent if r.get("state")}):
        vals = [v for r in recent if r.get("state") == state
                and (v := _num(r.get("value_aud_m"))) is not None]
        if len(vals) < MIN_SAMPLE:
            continue
        out["states"].append({
            "state": state, "n": len(vals), "total_aud_m": round(sum(vals), 1),
        })

    priced = [r for r in recent if _num(r.get("value_aud_m"))]
    if priced:
        big = max(priced, key=lambda r: _num(r.get("value_aud_m")))
        out["largest"] = {
            "headline": big.get("headline", ""),
            "value_aud_m": _num(big.get("value_aud_m")),
        }
    return out


def render(t: dict) -> str:
    """Deterministic HTML for the trend block. Empty string while data is thin."""
    if not t or not t.get("sectors"):
        return ""

    rows = []
    for s in t["sectors"]:
        if s["shift_bps"] is None:
            move = '<span style="color:#888;">n/a</span>'
        elif s["shift_bps"] < 0:
            move = (f'<span style="color:#1a7f37;font-weight:bold;">'
                    f'{s["shift_bps"]}bps</span>')  # tightening
        else:
            move = (f'<span style="color:#b04a1e;font-weight:bold;">'
                    f'+{s["shift_bps"]}bps</span>')
        rows.append(
            f'<tr><td style="padding:6px 10px 6px 0;">{s["sector"]}</td>'
            f'<td style="padding:6px 10px 6px 0;">{s["n"]}</td>'
            f'<td style="padding:6px 10px 6px 0;"><strong>'
            f'{s["median_yield"]}%</strong></td>'
            f'<td style="padding:6px 10px 6px 0;color:#666;">'
            f'{s["range"][0]}–{s["range"][1]}%</td>'
            f'<td style="padding:6px 0;">{move}</td></tr>'
        )

    states = ""
    if t["states"]:
        states = " · ".join(
            f'{s["state"]} ${s["total_aud_m"]:,.0f}m ({s["n"]})'
            for s in t["states"])
        states = (f'<p style="font-size:13px;color:#555;margin-top:8px;">'
                  f'Volume tracked by state: {states}</p>')

    return (
        '<h2>THE NUMBERS WE\'RE TRACKING</h2>'
        f'<p style="font-size:13px;color:#555;margin-bottom:8px;">'
        f'Computed from {t["total_tracked"]} transactions this brief has '
        f'recorded, {t["recent_count"]} in the last {t["window_days"]} days. '
        f'Movement compares the current cohort with the preceding one. '
        f'Green = tightening.</p>'
        '<table style="width:100%;border-collapse:collapse;font-size:14px;">'
        '<tr style="text-align:left;border-bottom:2px solid #e8b04b;">'
        '<th style="padding-bottom:4px;">Sector</th><th>Deals</th>'
        '<th>Median yield</th><th>Range</th><th>vs prior</th></tr>'
        f'{"".join(rows)}</table>{states}'
    )


def summary_for_editor(t: dict) -> str:
    """Plain-text digest handed to the editor so it can reference the figures."""
    if not t or not t.get("sectors"):
        return ("Trend database still accumulating — too few recorded "
                "transactions to publish medians. Do not invent trend figures.")
    bits = []
    for s in t["sectors"]:
        move = ("no prior cohort" if s["shift_bps"] is None else
                f'{s["shift_bps"]:+d}bps vs prior cohort')
        bits.append(f'{s["sector"]}: median {s["median_yield"]}% '
                    f'across {s["n"]} deals ({move})')
    return " | ".join(bits)
